keys:
  korrigan:
    token: blablabla

  tamere:
    token: tutututu

buckets:
  toto:
    path: /tmp/toto
    compress: 6
    allow:
      - korrigan
  tata:
    path: /tmp/tata
    allow:
      - tamere
  tutu:
    path: /tmp/tutu
    allow: all
